// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FollowAction1._0.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("FollowAction1._0.Models.Buyer", b =>
                {
                    b.Property<int>("idBuyer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .HasColumnType("TEXT");

                    b.HasKey("idBuyer");

                    b.ToTable("Buyer");
                });

            modelBuilder.Entity("FollowAction1._0.Models.BuyerAction", b =>
                {
                    b.Property<int>("idAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionTarget")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasColumnType("TEXT");

                    b.Property<int>("idBuyer")
                        .HasColumnType("INTEGER");

                    b.HasKey("idAction");

                    b.ToTable("BuyerAction");
                });

            modelBuilder.Entity("FollowAction1._0.Models.BuyerMovement", b =>
                {
                    b.Property<int>("idMovement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndPoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPoint")
                        .HasColumnType("TEXT");

                    b.Property<int>("idBuyer")
                        .HasColumnType("INTEGER");

                    b.HasKey("idMovement");

                    b.ToTable("BuyerMovement");
                });

            modelBuilder.Entity("FollowAction1._0.Models.Department", b =>
                {
                    b.Property<int>("idDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("idDepartment");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("FollowAction1._0.Models.Product", b =>
                {
                    b.Property<int>("idProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.Property<int>("idDepartment")
                        .HasColumnType("INTEGER");

                    b.HasKey("idProduct");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("FollowAction1._0.Models.Purchase", b =>
                {
                    b.Property<int>("idPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idBuyer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idProduct")
                        .HasColumnType("INTEGER");

                    b.HasKey("idPurchase");

                    b.ToTable("Purchase");
                });
#pragma warning restore 612, 618
        }
    }
}
